config/routes.rb
Ninmei::Application.routes.draw do
  devise_for :doctors

  resources :patients

  resources :appointments

  root to: 'pages#index'



  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  attr_accessible :date, :doctor_id, :patient_id, :reason

  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :title, :body

  def to_s
  	email
  end

  has_many :appointments
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :address, :dob, :name, :nhs_number

  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

	def new
		@appointment = Appointment.new
	end
	
	def create
		@appointment = Appointment.create(params[:appointment])
		if @appointment.save
			redirect_to appointments_url, notice: "Appointment added"
		else
			render :new
		end
	end

	def index
		@appointments = current_doctor.appointments.order(:date)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		@patients = Patient.all
	end

	def about
	end

	def contact
	end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
<h1>My Appointments</h1>

<hr/>

<ul>
	<% @appointments.each do |appointment| %>
		<li><%= appointment.date.to_s(:short) %> - <%= appointment.patient.name %> - <%= appointment.reason %></li>
	<%end%>
</ul>

app/views/appointments/new.html.erb
<h1>Add new appointment</h1>

<%= simple_form_for @appointment do |f| %>
	<%= f.input :reason, hint: 'Please make as specific as possible'%>
	<%= f.input :date %>
	<%= f.association :doctor, label_method: :email, prompt: 'Please choose a doctor' %>
	<%= f.association :patient, prompt: 'Please choose a patient' %>

	<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ninmei" %></title>
    <%= csrf_meta_tags %>


    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Ninmei</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Home", "/"  %></li>
              <li><%= link_to "About", "/about"  %></li>
              <li><%= link_to "Contact", "/contact"  %></li>

              <% if doctor_signed_in? %>
                <li><%= link_to "Patients", "/patients"  %></li>
                <li><%= link_to "Appointments", appointments_url %></li>
              <% end %>

              <% if doctor_signed_in? %>
                <li><%= link_to "Sign out", destroy_doctor_session_url, method: :delete %></li>
              <% else %>
                <li><%= link_to "Sign in", "/doctors/sign_in" %></li>
                <li><%= link_to "Register", "/doctors/sign_up" %></li>
              <% end %>

            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Ninmei</h3>
              <ul class="nav nav-list">
                <li class="nav-header"></li>
                <li><%= link_to "Patients", "/patients"  %></li>
                <li class="btn"><%= link_to "Add new appointment", new_appointment_url %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Ninmei 2013</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About Ninmei</h1>

Ninmei is a basic appointments scheduler

app/views/pages/contact.html.erb
<h1>Contact Ninmei</h1>

<h3>Twitter: @ninmei</h3>
<h3>IRC: freenode ninmei</h3>
<h3>Postal: can you really be bothered finding a stamp?</h3>
 

app/views/pages/index.html.erb
<h1>Welcome to Ninmei</h1>

<h3>Current time: <%= Time.now %> </h3>

<h3>The number of patients in the system is <%= @patients.count %> </h3>

app/views/patients/_form.html.erb
<%= form_for @patient, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :dob, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :dob, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :address, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :address, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :nhs_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nhs_number, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                patients_path, :class => 'btn' %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/patients/index.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:dob) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:nhs_number) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to patient.id, patient_path(patient) %></td>
        <td><%= patient.name %></td>
        <td><%= patient.dob %></td>
        <td><%= patient.address %></td>
        <td><%= patient.nhs_number %></td>
        <td><%=l patient.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_patient_path(patient), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      patient_path(patient),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_patient_path,
            :class => 'btn btn-primary' %>

app/views/patients/new.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/patients/show.html.erb
<%- model_class = Patient -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @patient.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dob) %>:</strong></dt>
  <dd><%= @patient.dob %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @patient.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nhs_number) %>:</strong></dt>
  <dd><%= @patient.nhs_number %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              patients_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_patient_path(@patient), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              patient_path(@patient),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>